web:
    build: .
    dockerfile: Dockerfile.nginx
    ports: 
        - "8080:8080"
mongodb:
    image: mongo:3.0
    ports:
        - "27017"
    volumes:
        - "/data/db"
girder:
    build: .
    dockerfile: Dockerfile
    links:
        - "mongodb:mongodb"
        - web:web
    command: -p 8888 -d mongodb://mongodb:27017/girder