mongodb:
    image: mongo:3.4
    ports:
        - "27017"
    volumes:
        - "/data/db"
girder:
    build: ./girder
    dockerfile: Dockerfile
    links:
        - "mongodb:mongodb"
    command: -d mongodb://mongodb:27017/girder
web:
    build: ./nginx
    dockerfile: Dockerfile
    ports:
        - "8080:80"
    links:
        - "girder:girder"
